#!/bin/sh

why=$1
provers="simplify zenon harvey cvcl"

echo "Checking provers outputs"

rm -f *_why.sx *_why.znn *_why.rv *.baf *_why.cvc

for f in *.mlw; do
    if test $f = loop_monomorph.mlw; then break; fi
    echo -n "$f: "
    for p in $provers; do
	echo -n $p...
	if ! $why --$p $f > /dev/null 2>&1; then
	    echo "why --$p FAILED"
	    $why --$p $f
	    exit 1
	else
	    echo -n "ok "
	fi
    done
    echo
done
dp *_why.sx 2>/dev/null
dp *_why.znn 2>/dev/null
dp *_why.cvc 2>/dev/null
dp *_why.rv 2>/dev/null

 