#!/bin/bash

# For matching file names on file systems without case distinction (e.g. case-insensitive HFS)
shopt -s nocasematch

RESULT=$(ocamlfind ocamldep $@)
STATUS=$?
PREFIXED=""
if [[ "$RESULT" =~ src/jc/jc_.*\.mli?:.* ]]; then
    for i in $RESULT; do
        [[ "$i" =~ .*: || "$i" =~ Why_[^o].* ]] || PREFIXED="$PREFIXED Jc_${i,}"
    done
fi
echo $RESULT $PREFIXED
exit $STATUS
