#!/bin/sh

FILES=`cat bench-files`

# benchmark for caduceus
export CADUCEUSLIB=`pwd`/../../lib/why
export WHYCOQ=`pwd`/../../lib/coq
make="make WHYCOQ=$WHYCOQ"

cd good
export CADUCEUSLIB=`pwd`/../../../lib

bench_c_good () {
    options="$* -why-opt -split-user-conj " # -why-opt -show-time"  # --typing-predicates"
    echo "-------------------------------------------------------------------"
    echo "Bench Caduceus+Simplify/Yices with options: $options"
    parsing="../../../bin/caduceus.opt $options"

    rm -f why/*.why
    rm -f simplify/*_why.sx
    rm -f smtlib/*_why.smt
    rm -f *.time
    CADUCEUS=$parsing make -e -j 7 -f Makefile.bench
}

bench_c_good
# bench_c_good -separation -no-zone-type
bench_c_good -separation

