#!/bin/sh

echo "Bench Frama-C + Jessie plugin"
echo "Date: "`LANG=C date`

files=`ls *.c`

dpfiles=""
fail=""

for c in $files ; do 
    f=`basename $c .c`
    d=$f.jessie
    g=$f"_why"
    for h in simplify/$g.sx why/$g.why smtlib/$g.smt ; do
    # simplify only: for h in simplify/$g.sx ; do
    	rm -f $d/$h
    	make --quiet -C $d -f $f.makefile $h
	if test -e $d/$h ; then
	   dpfiles=$dpfiles" "$d/$h
	else		     
	   fail=$fail" "$f
	fi   
    done
done

echo "****************************************"
echo "VCgen failed on:"$fail
echo "****************************************"
why-dp -basename -timeout 10 -smt-solver z3 $dpfiles

