.TH why 1 "March, 2002"

.SH NAME
why \- A certification tool


.SH SYNOPSIS
.B why
[
.B options
]
.B files


.SH DESCRIPTION

.B why
is a certification tool for the PVS and Coq proof assistants.
It takes annotated programs as input, in ML syntax.

.SH OPTIONS

.TP
.B \-h
Help. Will give you the complete list of options accepted by why.


.SH AUTHORS
.I Jean-Christophe Filliatre <filliatr@lri.fr>


.SH SEE ALSO

.I
Why web site: http://www.lri.fr/~filliatr/why/
