.TH why 1 "September, 2003"

.SH NAME
why2html \- Converts Why input files to HTML


.SH SYNOPSIS
.B why2html
[
.B -t title
]
.B files


.SH DESCRIPTION

.B why2html
converts Why input files to HTML.
Each file
.I foo
on the command line is converted into a HTML file
.I foo.html


.SH OPTIONS

.TP
.B \-t title
Specifies a title for the HTML page.


.SH AUTHORS
.I Jean-Christophe Filliatre <filliatr@lri.fr>


.SH SEE ALSO
.BR why (1)

.I
Why web site: http://www.lri.fr/~filliatr/why/
