(* This file was originally generated by why.
   It can be modified; only the generated parts will be overwritten. *)

Require Import Why.
Require Import Omega.

Proof.
tauto.
Qed.

Proof.
intros; ArraySubst t0.
Qed.


Proof.
intros; subst t1 t0 v.
auto with datatypes.
Qed.


