(* This file was originally generated by why.
   It can be modified; only the generated parts will be overwritten. *)

Require Export swap_spec_why.

(* Why obligation from file "", line 0, characters 0-0: *)
(*Why goal*) Lemma swap_impl_po_1 : 
  forall (c: ((pointer) Z21)),
  forall (alloc: alloc_table),
  forall (tl_Z21: ((memory) ((pointer) Z21) Z21)),
  forall (HW_1: (* File "swap.c", line 3, characters 14-64 *)
                (exists l:plist, (llist tl_Z21 alloc c l) /\
                 (list_length l) >= 2)),
  forall (HW_3: ~(c = null)),
  forall (p: ((pointer) Z21)),
  forall (HW_4: p = c),
  (valid alloc c).
Proof.
intuition.
inversion_clear HW_1; intuition.
inversion H0; intuition.
Save.

(* Why obligation from file "", line 0, characters 0-0: *)
(*Why goal*) Lemma swap_impl_po_2 : 
  forall (c: ((pointer) Z21)),
  forall (alloc: alloc_table),
  forall (tl_Z21: ((memory) ((pointer) Z21) Z21)),
  forall (HW_1: (* File "swap.c", line 3, characters 14-64 *)
                (exists l:plist, (llist tl_Z21 alloc c l) /\
                 (list_length l) >= 2)),
  forall (HW_3: ~(c = null)),
  forall (p: ((pointer) Z21)),
  forall (HW_4: p = c),
  forall (HW_5: (valid alloc c)),
  forall (result: ((pointer) Z21)),
  forall (HW_6: result = (acc tl_Z21 c)),
  forall (mutable_c: ((pointer) Z21)),
  forall (HW_7: mutable_c = result),
  (valid alloc mutable_c).
Proof.
intuition; subst; auto.
inversion_clear HW_1; intuition.
inversion H0; subst; intuition.
inversion H3; subst; intuition.
elimtype False.
unfold list_length in H1.
simpl in H1.
auto.
Save.

(* Why obligation from file "", line 0, characters 0-0: *)
(*Why goal*) Lemma swap_impl_po_3 : 
  forall (c: ((pointer) Z21)),
  forall (alloc: alloc_table),
  forall (tl_Z21: ((memory) ((pointer) Z21) Z21)),
  forall (HW_1: (* File "swap.c", line 3, characters 14-64 *)
                (exists l:plist, (llist tl_Z21 alloc c l) /\
                 (list_length l) >= 2)),
  forall (HW_3: ~(c = null)),
  forall (p: ((pointer) Z21)),
  forall (HW_4: p = c),
  forall (HW_5: (valid alloc c)),
  forall (result: ((pointer) Z21)),
  forall (HW_6: result = (acc tl_Z21 c)),
  forall (mutable_c: ((pointer) Z21)),
  forall (HW_7: mutable_c = result),
  forall (HW_8: (valid alloc mutable_c)),
  forall (result0: ((pointer) Z21)),
  forall (HW_9: result0 = (acc tl_Z21 mutable_c)),
  (valid alloc p).
Proof.
intuition.
subst; auto.
Save.

(* Why obligation from file "", line 0, characters 0-0: *)
(*Why goal*) Lemma swap_impl_po_4 : 
  forall (c: ((pointer) Z21)),
  forall (alloc: alloc_table),
  forall (tl_Z21: ((memory) ((pointer) Z21) Z21)),
  forall (HW_1: (* File "swap.c", line 3, characters 14-64 *)
                (exists l:plist, (llist tl_Z21 alloc c l) /\
                 (list_length l) >= 2)),
  forall (HW_3: ~(c = null)),
  forall (p: ((pointer) Z21)),
  forall (HW_4: p = c),
  forall (HW_5: (valid alloc c)),
  forall (result: ((pointer) Z21)),
  forall (HW_6: result = (acc tl_Z21 c)),
  forall (mutable_c: ((pointer) Z21)),
  forall (HW_7: mutable_c = result),
  forall (HW_8: (valid alloc mutable_c)),
  forall (result0: ((pointer) Z21)),
  forall (HW_9: result0 = (acc tl_Z21 mutable_c)),
  forall (HW_10: (valid alloc p)),
  forall (tl_Z21_0: ((memory) ((pointer) Z21) Z21)),
  forall (HW_11: tl_Z21_0 = (upd tl_Z21 p result0)),
  (valid alloc mutable_c).
Proof.
intuition.
Save.

(* Why obligation from file "", line 0, characters 0-0: *)
(*Why goal*) Lemma swap_impl_po_5 : 
  forall (c: ((pointer) Z21)),
  forall (alloc: alloc_table),
  forall (tl_Z21: ((memory) ((pointer) Z21) Z21)),
  forall (HW_1: (* File "swap.c", line 3, characters 14-64 *)
                (exists l:plist, (llist tl_Z21 alloc c l) /\
                 (list_length l) >= 2)),
  forall (HW_3: ~(c = null)),
  forall (p: ((pointer) Z21)),
  forall (HW_4: p = c),
  forall (HW_5: (valid alloc c)),
  forall (result: ((pointer) Z21)),
  forall (HW_6: result = (acc tl_Z21 c)),
  forall (mutable_c: ((pointer) Z21)),
  forall (HW_7: mutable_c = result),
  forall (HW_8: (valid alloc mutable_c)),
  forall (result0: ((pointer) Z21)),
  forall (HW_9: result0 = (acc tl_Z21 mutable_c)),
  forall (HW_10: (valid alloc p)),
  forall (tl_Z21_0: ((memory) ((pointer) Z21) Z21)),
  forall (HW_11: tl_Z21_0 = (upd tl_Z21 p result0)),
  forall (HW_12: (valid alloc mutable_c)),
  forall (tl_Z21_1: ((memory) ((pointer) Z21) Z21)),
  forall (HW_13: tl_Z21_1 = (upd tl_Z21_0 mutable_c p)),
  (* File "swap.c", line 4, characters 13-146 *)
  (forall (l:plist),
   (forall (c1:((pointer) Z21)),
    (forall (c2:((pointer) Z21)),
     ((llist tl_Z21 alloc c (cons c1 (cons c2 l))) ->
      (llist tl_Z21_1 alloc mutable_c (cons c2 (cons c1 l))))))).
Proof.
unfold cons ,llist, lpath; intuition; subst; auto.
inversion_clear H.
assert (~ In c1 (c2::l)).
   apply llist_not_starting with (next := acc tl_Z21) (1:=H2).
assert (c1<>c2).
  red in H; simpl in H; auto.
assert (c2 = c1 # tl_Z21).
  inversion H2; auto.
subst.
inversion_clear H2.
apply Path_cons; auto.
caduceus.
apply Path_cons; auto.
caduceus.
apply lpath_pset_same; auto.
apply lpath_pset_same; auto.
intro; apply H.
simpl; auto.
apply llist_not_starting with (next := acc tl_Z21) (1:=H6).
Save.

(* Why obligation from file "", line 0, characters 0-0: *)
(*Why goal*) Lemma swap_impl_po_6 : 
  forall (c: ((pointer) Z21)),
  forall (alloc: alloc_table),
  forall (tl_Z21: ((memory) ((pointer) Z21) Z21)),
  forall (HW_1: (* File "swap.c", line 3, characters 14-64 *)
                (exists l:plist, (llist tl_Z21 alloc c l) /\
                 (list_length l) >= 2)),
  forall (HW_14: c = null),
  (* File "swap.c", line 4, characters 13-146 *)
  (forall (l:plist),
   (forall (c1:((pointer) Z21)),
    (forall (c2:((pointer) Z21)),
     ((llist tl_Z21 alloc c (cons c1 (cons c2 l))) ->
      (llist tl_Z21 alloc c (cons c2 (cons c1 l))))))).
Proof.
intuition.
elimtype False.
clear H c2 c1.
inversion_clear HW_1.
inversion_clear H.
subst.
inversion H0; auto.
subst x.
auto.
Save.

