
WHY=../../bin/why.static
WHYOPTIONS=--valid

%_why.v: %.mlw $(WHY)
	$(WHY) $(WHYOPTIONS) $<

%.vo: %.v
	coqc -R ../../lib/coq Coq.why $<

%_why.pvs: %.mlw $(WHY)
	$(WHY) --pvs $(WHYOPTIONS) $<

%.ml: %.mlw
	$(WHY) -ocaml $< > $@
	ocamlc -c -i $@

clean::
	rm -f *~ *.vo

depend::
	coqdep -R ../../lib/coq Coq.why *.v > .depend

include .depend
