
WHY=../../bin/why.static
WHYOPTIONS=--valid

%_why.v: %.ml $(WHY)
	$(WHY) $(WHYOPTIONS) $<

%.vo: %.v
	coqc -I ../../lib/coq $<

%_why.pvs: %.ml $(WHY)
	$(WHY) --pvs $(WHYOPTIONS) $<

clean::
	rm -f *~ *.vo

depend::
	coqdep -I ../../lib/coq *.v > .depend

include .depend
