(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require Jessie_pointer.
Require int.Int.
Require map.Map.
Require Jessie_tag_id.
Require Jessie_tag.
Require Jessie_tag_table_type.
Require Jessie_voidp.
Require Jessie_voidp_tag_id.
Require Jessie_tag_table.

Parameter charP_tag: (Jessie_tag_id.tag_id Jessie_voidp.voidP).

Axiom Charp_int : ((Jessie_tag_id.int_of_tag charP_tag) = 2%Z).

Axiom Charp_is_final : forall (t:(map.Map.map (Jessie_pointer.pointer
  Jessie_voidp.voidP) (Jessie_tag_id.tag_id Jessie_voidp.voidP))),
  forall (p:(Jessie_pointer.pointer Jessie_voidp.voidP)),
  (Jessie_tag_table.instanceof t p charP_tag) -> ((map.Map.get t
  p) = charP_tag).

Axiom Charp_parenttag_voidp : (Jessie_tag.parenttag charP_tag
  Jessie_voidp_tag_id.voidP_tag).

