(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require Jessie_pointer.
Require int.Int.
Require Jessie_alloc_table.
Require Jessie_memory.
Require map.Map.
Require Jessie_pset.
Require Jessie_assigns.

(* Why3 assumption *)
Definition not_assigns_strong {t:Type} {t_WT:WhyType t}
  {v:Type} {v_WT:WhyType v} (m1:(map.Map.map (Jessie_pointer.pointer t) v))
  (m2:(map.Map.map (Jessie_pointer.pointer t) v)) (l:(Jessie_pset.pset
  t)): Prop := forall (p:(Jessie_pointer.pointer t)), (~ (Jessie_pset.in_pset
  p l)) -> ((map.Map.get m2 p) = (map.Map.get m1 p)).

Axiom not_assigns_strong1 : forall {t:Type} {t_WT:WhyType t}
  {v:Type} {v_WT:WhyType v}, forall (m1:(map.Map.map (Jessie_pointer.pointer
  t) v)), forall (m2:(map.Map.map (Jessie_pointer.pointer t) v)),
  forall (l:(Jessie_pset.pset t)), (not_assigns_strong m1 m2 l) ->
  forall (a1:(Jessie_alloc_table.alloc_table t)),
  forall (a2:(Jessie_alloc_table.alloc_table t)), (Jessie_assigns.not_assigns
  a1 a2 m1 m2 l).

