(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require Jessie_pointer.
Require int.Int.
Require map.Map.
Require Jessie_tag_id.
Require Jessie_tag_table_type.
Require Jessie_voidp.

Parameter voidP_tag: (Jessie_tag_id.tag_id Jessie_voidp.voidP).

Axiom Voidp_int : ((Jessie_tag_id.int_of_tag voidP_tag) = 0%Z).

