(* This file was originally generated by why.
   It can be modified; only the generated parts will be overwritten. *)

Require Export Caduceus.

































(*Why type*) Definition Z0: Set.
Admitted.

(*Why predicate*) Definition purse_inv  (alloc:alloc_table)
  (p:((pointer) Z0))
  := (* File "purse.c", line 6, characters 37-65 *) ((valid alloc p) /\
     (acc balance_Z0 p) >= 0).

