
all: swap0_valid.vo loop0_valid.vo peano_valid.vo power_valid.vo \
     arith_valid.vo mac_carthy_valid.vo fib_valid.vo gcd_valid.vo \
     flag_valid.vo search_valid.vo sqrt_dicho_valid.vo csearch_valid.vo \
     copy_valid.vo max_why.vo

include ../Makefile.common
