(* This file was originally generated by why.
   It can be modified; only the generated parts will be overwritten. *)

Require Import Why.

Lemma mean1 : forall x y:Z, (x <= y)%Z -> (x <= (x + y) / 2)%Z.
Proof.
intros.
assert ((x + y) / 2 >= (x + x) / 2)%Z.
apply Z_div_ge; omega.
assert (((x + x) / 2)%Z = x); auto with *.
replace (x + x)%Z with (0 + x * 2)%Z; auto with *.
rewrite (Z_div_plus 0 x 2); auto with *.
Qed.

Lemma mean2 : forall x y:Z, (x < y)%Z -> ((x + y) / 2 < y)%Z.
Proof.
intros.
apply (Zmult_lt_reg_r ((x + y) / 2) y) with (p:=2).
auto with *.
replace ((x + y) / 2 * 2)%Z with (2 * ((x + y) / 2))%Z; auto with *.
assert (2 * ((x + y) / 2) <= x + y)%Z.
apply (Z_mult_div_ge (x + y) 2).
auto with *.
omega.
Qed.

Hint Resolve mean1 mean2 .

Proof.
intuition.
Qed.

Proof.
intuition.
subst sup2; trivial.
subst mil2 sup2.
replace (inf1 + (sup1 + 1))%Z with (inf1 + (sup1 - 1) + 1 * 2)%Z;
 try omega.
rewrite Z_div_plus; try omega.
assert (inf1 <= (inf1 + (sup1 - 1)) / 2)%Z.
apply mean1; omega.
omega.
unfold Zwf.
split; try omega.
subst mil2 sup2.
 replace (inf1 + (sup1 + 1))%Z with (inf1 + 1 + sup1)%Z; try omega.
assert ((inf1 + 1 + sup1) / 2 < sup1)%Z.
apply mean2; omega.
omega.
Qed.

Proof.
intuition.
subst mil2 inf2; omega.
subst mil2 inf2.
replace (inf1 + (sup1 + 1))%Z with (inf1 + 1 + sup1)%Z; try omega.
assert ((inf1 + 1 + sup1) / 2 < sup1)%Z.
apply mean2; omega.
omega.
unfold Zwf; split; try omega.
subst inf2 mil2.
replace (inf1 + (sup1 + 1))%Z with (inf1 + 1 + sup1)%Z; try omega.
assert (inf1 + 1 <= (inf1 + 1 + sup1) / 2)%Z.
apply mean1; omega.
omega.
Qed.

Proof.
intuition; subst; auto.
Qed.

Proof.
intuition.
subst inf; omega.
subst sup.
ring ((x + 1) * (x + 1))%Z.
assert (0 <= x * x)%Z.
auto with *.
omega.
Qed.


